NASA_API#startInstancesWhenFlowStarts
NASA_API#WebForecast_API = http://api.openweathermap.org/geo/1.0/zip
NASA_API#Nasa Input.URLSpecifier = /weatherforecast/getdata
NASA_API#Nasa Input.useHTTPS
NASA_API#Compute1.dataSource
NASA_API#Compute1.connectDatasourceBeforeFlowStarts
NASA_API#Compute1.validateMaster
NASA_API#File Output.outputDirectory = C:\Users\FAROOK\OneDrive\Desktop\WeatherForeCast
NASA_API#File Output.outputFilename = Nasa_Error.log
NASA_API#File Output.fileFtpUser
NASA_API#File Output.fileFtpDirectory
NASA_API#HTTP Request.URLSpecifier = http://api.openweathermap.org/geo/1.0/direct
NASA_API#HTTP Request.timeoutForServer
NASA_API#HTTP Request.httpProxyLocation
NASA_API#HTTP Request.httpVersion
WeatherForecast_zipCode#securityProfileName
WeatherForecast_zipCode#monitoringProfile
WeatherForecast_zipCode#startMode
WeatherForecast_zipCode#startInstancesWhenFlowStarts
WeatherForecast_zipCode#File Input.inputDirectory = C:\Users\FAROOK\OneDrive\Desktop\WeatherForeCast\Input
WeatherForecast_zipCode#File Input.recursiveDirectories
WeatherForecast_zipCode#File Input.filenamePattern = *.txt
WeatherForecast_zipCode#File Input.excludePattern
WeatherForecast_zipCode#File Input.messageCodedCharSetIdProperty
